fix path problems which lead to new projects not running
boydm/scenic_driver_glfw pull request #26
Opened 2019-07-18 02:02 UTC by ejc123

This is a potential fix for #25 and a similar bug [in scenic](https://github.com/boydm/scenic_new/issues/36).  I have tested it with a fresh project generated from mix scenic.new.example as well as mix scenic.new and it works with both MIX_ENV=prod or MIX_ENV=dev, first time and further times.

2019-07-18 11:00 UTC, Eiji7 requested changes

2019-07-18 11:00 UTC, Eiji7 commented on Makefile
>  	$(RM) -r priv/dev
Why you are not changing `priv` with `${RPEFIX}` in `clean` target? Also why instead of using `${MIX_ENV}` we have remove call for every environment? Also what if we have a custom `${MIX_ENV}`? From what I can see it would be not cleaned properly …

2019-07-19 11:12 UTC, ejc123 commented on Makefile
>  	$(RM) -r priv/dev
Thank you.  I hadn't even thought of doing that.  Changed committed.

2019-07-19 23:28 UTC, boydm commented
Are you able to get `mix test` to run? It is failing to find the executable in the test environment for me...

2019-07-19 23:29 UTC, boydm commented
Also... I really appreciate the help with this!

2019-07-20 21:38 UTC, Eiji7 approved these changes
Personally I would change all tabulations to 2 spaces and store `scenic_driver_glfw` under `PROJECT_NAME` variable, but it's not something as important as making it working. I have tested it and it works for me as well, so for me it could be approved.

2019-07-20 21:38 UTC, Eiji7 commented
@boydm Just tried it and `mix test` works for me (for both example projects and this project standalone). Can you please copy your whole compilation output?

2019-07-20 21:41 UTC, boydm commented
@eiji7

```
[scenic_driver_glfw (ejc123-master)]$ mix test
mkdir -p /Users/boyd/git/scenic/split/scenic_driver_glfw/_build/test/lib/scenic_driver_glfw/ebin/../priv/test
cc -O3 -std=c99 `pkg-config --static --cflags glfw3 glew` -fPIC -o /Users/boyd/git/scenic/split/scenic_driver_glfw/_build/test/lib/scenic_driver_glfw/ebin/../priv/test/scenic_driver_glfw c_src/main.c c_src/comms.c c_src/nanovg/nanovg.c c_src/utils.c c_src/render_script.c c_src/tx.c `pkg-config --static --libs glfw3 glew` -framework Cocoa -framework OpenGL -Wno-deprecated
Compiling 7 files (.ex)
Generated scenic_driver_glfw app
sh: /Users/boyd/git/scenic/split/scenic_driver_glfw/_build/test/lib/scenic_driver_glfw/priv/test/scenic_driver_glfw: No such file or directory
sh: line 0: exec: /Users/boyd/git/scenic/split/scenic_driver_glfw/_build/test/lib/scenic_driver_glfw/priv/test/scenic_driver_glfw: cannot execute: No such file or directory


  1) test Integration style test (Scenic.Driver.GlfwTest)
     test/glfw_test.exs:35
     Assertion with == failed
     code:  assert Glfw.Cache.load_static_texture(@parrot_hash, state.port()) == true
     left:  nil
     right: true
     stacktrace:
       test/glfw_test.exs:69: (test)

Finished in 1.7 seconds
1 test, 1 failure
```

Randomized with seed 320809
[scenic_driver_glfw (ejc123-master)]$

2019-07-20 22:14 UTC, Eiji7 commented
@boydm Of course except parent directory and compilation flags (I have no MacOS) all paths are exactly same. After `Generated scenic_driver_glfw app` I can see that tests finished successfully (I saw window without problem). For sure here is my output:

```bash
$ mix test
mkdir -p /home/eiji/scenic_driver_glfw/_build/test/lib/scenic_driver_glfw/ebin/../priv/test
cc -O3 -std=c99 `pkg-config --static --cflags glfw3 glew` -fPIC -o /home/eiji/scenic_driver_glfw/_build/test/lib/scenic_driver_glfw/ebin/../priv/test/scenic_driver_glfw c_src/main.c c_src/comms.c c_src/nanovg/nanovg.c c_src/utils.c c_src/render_script.c c_src/tx.c `pkg-config --static --libs glfw3 glew` -lGL -lm -lrt
.

Finished in 3.8 seconds
1 test, 0 failures

Randomized with seed 681971
```

2019-07-20 22:19 UTC, axelson commented
@boydm Interesting, I'm only able to get that error intermittently, but only on the master branch so far (instead of this PR), not sure how to reproduce it. I've been able to get the error on both Mac OS and Linux. What version of Elixir and Erlang are you using? I've tested with Elixir 1.8.1-otp-21 (w Erlang 21.2.4) and Elixir 1.9.1-otp-22 (w Erlang 22.0.7).

2019-07-20 22:21 UTC, boydm commented
@axelson
OTP 22 and elixir 1.9.0

I'll update to 1.9.1 and see what happens...

2019-07-20 22:30 UTC, Eiji7 commented
@axelson Can you please give me a steps to reproduce?

2019-07-20 22:32 UTC, boydm commented
Same with 1.9.1.

2019-07-20 23:35 UTC, Eiji7 commented
Hmm … I have tried different `Erlang` and `Elixir` versions. For now I have:
```elixir
$ asdf current
elixir         1.9.1-otp-22 (set by …)
erlang         22.0.7   (set by …)
…
```
I still can't reproduce this problem. @axelson said that he got error also on `Linux`, but tried lots of times and I'm unable to reproduce it. I have pulled `axelson/scenic_driver_glfw` and even changed in `mix.exs` dependency `scenic` to fetch it from `github` i.e. `github: "boydm/scenic"` does not changes result.

2019-07-21 01:08 UTC, axelson commented
I'm only able to reproduce the error on master with `rm -rf _build; rm -rf priv; git checkout priv; mix test`. But it's not actually the same error since on master gcc is outputting to `priv/test/scenic_driver_glfw` whereas on this branch it outputs to the full build directory.

The only thing I can think of is if Boyd's `ebin` folder is a symlink because otherwise the `cc` invocation is putting the binary into `/Users/boyd/git/scenic/split/scenic_driver_glfw/_build/test/lib/scenic_driver_glfw/ebin/../priv/test/scenic_driver_glfw`, which should match the path `/Users/boyd/git/scenic/split/scenic_driver_glfw/_build/test/lib/scenic_driver_glfw/priv/test/scenic_driver_glfw`

@boydm do you still have errors if you `rm -rf _build deps`.

The other weird thing I've noticed is that if I `cp -r _build/test/lib/scenic_driver_glfw/priv/test priv` then I will get `make: Nothing to be done for 'all'.`, when I would expect that to not matter.

2019-07-21 01:46 UTC, Eiji7 commented
Sorry I'm just lost or did something amazing accidentally :smile:

Your example:
```bash
rm -rf _build; rm -rf priv; git checkout priv; mix test
```
gives me exactly same results i.e. tests works. To make sure I have tried few times.

> But it's not actually the same error since on master gcc is outputting to priv/test/scenic_driver_glfw whereas on this branch it outputs to the full build directory.

Sorry, I did not get this, because:
```bash
# master
$ git clone https://github.com/ejc123/scenic_driver_glfw.git
$ mix deps.get
$ mix test
cc -O3 -std=c99 `pkg-config --static --cflags glfw3 glew` -fPIC -o /home/eiji/scenic_driver_glfw/_build/test/lib/scenic_driver_glfw/ebin/../priv/test/scenic_driver_glfw c_src/main.c c_src/comms.c c_src/nanovg/nanovg.c c_src/utils.c c_src/render_script.c c_src/tx.c `pkg-config --static --libs glfw3 glew` -lGL -lm -lrt
# priv
$ rm -rf _build; rm -rf priv; git checkout priv; mix test
cc -O3 -std=c99 `pkg-config --static --cflags glfw3 glew` -fPIC -o /home/eiji/scenic_driver_glfw/_build/test/lib/scenic_driver_glfw/ebin/../priv/test/scenic_driver_glfw c_src/main.c c_src/comms.c c_src/nanovg/nanovg.c c_src/utils.c c_src/render_script.c c_src/tx.c `pkg-config --static --libs glfw3 glew` -lGL -lm -lrt
```

As you can see on both branches `gcc` gives me full build directory … It's probably why I can't reproduce this problem, right?

2019-07-21 01:47 UTC, axelson commented
Sorry, by `master` I mean commit `4e5b0d9` from https://github.com/boydm/scenic_driver_glfw

2019-07-21 01:55 UTC, Eiji7 commented
@axelson ok, got it!

Sorry, I though that we are talking about this PR only which points to your repository :smile:

On "master" I have now:
```bash
mkdir -p priv/test
cc -O3 -std=c99 `pkg-config --static --cflags glfw3 glew` -fPIC -o priv/test/scenic_driver_glfw c_src/main.c c_src/comms.c c_src/nanovg/nanovg.c c_src/utils.c c_src/render_script.c c_src/tx.c `pkg-config --static --libs glfw3 glew` -lGL -lm -lrt
Compiling 7 files (.ex)
Generated scenic_driver_glfw app
sh: /home/eiji/scenic_driver_glfw/_build/test/lib/scenic_driver_glfw/priv/test/scenic_driver_glfw: Nie ma takiego pliku ani katalogu

# + of course failed test
```

2019-07-21 01:58 UTC, Eiji7 commented
Looks like same goes to `priv` branch:
```bash
mkdir -p priv/test
cc -O3 -std=c99 `pkg-config --static --cflags glfw3 glew` -fPIC -o priv/test/scenic_driver_glfw c_src/main.c c_src/comms.c c_src/nanovg/nanovg.c c_src/utils.c c_src/render_script.c c_src/tx.c `pkg-config --static --libs glfw3 glew` -lGL -lm -lrt
Compiling 7 files (.ex)
Generated scenic_driver_glfw app
# again from Polish: no such file or directory
sh: /home/eiji/scenic_driver_glfw/_build/test/lib/scenic_driver_glfw/priv/test/scenic_driver_glfw: Nie ma takiego pliku ani katalogu

# again + of course failed test
```

2019-07-21 02:14 UTC, Eiji7 commented
@axelson I think that I found problem, but I'm not sure …

In my opinion we have 2 problems:
1. First time building
2. Building after **only** `make clean`

In 1st case we have compiled `scenic_driver_glfw` binary and `mix` does not copies it to `_build/${Mix.env}/lib/scenic_driver_glfw/priv/${Mix.env}` directory. That's said even `_build/${Mix.env}/lib/scenic_driver_glfw/priv/${Mix.env}` is not created!

The problem is that `:code.priv_dir(:app_name)` points to `_build/${Mix.env}/lib/app_name/priv` instead of `priv`.

In 2nd point we have a similar case i.e. binary is created properly without any problem, but not copied by `mix`:

```bash
$ make clean
rm -f -r priv/dev
rm -f -r priv/test
rm -f -r priv/prod
$ mix test
mkdir -p priv/test
cc -O3 -std=c99 `pkg-config --static --cflags glfw3 glew` -fPIC -o priv/test/scenic_driver_glfw c_src/main.c c_src/comms.c c_src/nanovg/nanovg.c c_src/utils.c c_src/render_script.c c_src/tx.c `pkg-config --static --libs glfw3 glew` -lGL -lm -lrt
# again from Polish: no such file or directory
sh: /home/eiji/scenic_driver_glfw/_build/test/lib/scenic_driver_glfw/priv/test/scenic_driver_glfw: Nie ma takiego pliku ani katalogu
```

2019-07-21 07:12 UTC, josevalim commented
Please make sure to bump elixifr_make requirement in mix.exs.

2019-07-21 07:16 UTC, boydm commented
Thank you @josevalim!
I bumped the deps to       {:elixir_make, "~> 0.6"},
And the problem has gone away. Yay!

@ejc123 please add that update to the mix.exs file and lets get this into a release.

Thank you all!

2019-07-21 07:30 UTC, josevalim commented on Makefile
> +PREFIX=$(MIX_COMPILE_PATH)/../priv
```suggestion
PREFIX=$(MIX_APP_PATH)/priv
```

2019-07-21 09:23 UTC, axelson commented
Ah, so the issue was that boyd and I were not running the same version of elixir_make. Would it make sense to commit the `mix.lock` file to help avoid issues like that in the future?

2019-07-21 09:23 UTC, boydm commented
@axelson I was just thinking the same thing

2019-07-21 13:07 UTC, boydm commented
Too tired to get this in tonight. Don't want to make mistakes. Tomorrow...

2019-07-21 18:04 UTC, axelson commented
Also for future reference, I believe this is the PR that we needed to bring in from elixir_make: https://github.com/elixir-lang/elixir_make/pull/32

2019-07-22 03:25 UTC, Eiji7 commented
@axelson Yes, I think so - it's how José see `priv` working

2019-07-22 07:11 UTC, boydm approved these changes

2019-07-22 07:15 UTC, merged

2019-07-22 07:16 UTC, boydm commented
Hey all. This is now in master. I added Jose's suggestion and make sure the dep on elixir_make is 0.6.

If I could get some confirmations that master works for you on the various systems you use, that would be great. I'll publish an update some time after that.

2019-07-22 10:39 UTC, Eiji7 commented
@boydm I just tested it:

1. `mix test` on master works!
2. `mix scenic.new.example example; cd example; mix scenic.run` don't work (as expected - i.e. not master)
3. changing `scenic_driver_glfw` to `master` in `mix.exs` for `example` from 2nd point and run `mix scenic.run` works!

My environment:

```bash
$ asdf current
elixir         1.9.1-otp-22 (set by …)
erlang         22.0.7   (set by …)
…
```

Funtoo Linux current x86-64bit on intel64-ivybridge

2019-07-22 18:19 UTC, axelson commented
@boydm okay, tested scenic.new and my scenic_asteroids repositories with the master branch of `scenic_driver_glfw` on both Arch Linux and Mac OS 10.14 and they're working great. Although there is a similar issue with scenic_driver_nerves_rpi which I've filed as https://github.com/boydm/scenic_driver_nerves_rpi/issues/10

2019-07-28 03:20 UTC, boydm commented
This is now published in v0.10.1 to hex